// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc3ydqMvQywtBVhRhoLqgJikV1z-41vpY',
    appId: '1:585831821490:web:fb395712042dc59f6899ab',
    messagingSenderId: '585831821490',
    projectId: 'gameclass-6f9ab',
    authDomain: 'gameclass-6f9ab.firebaseapp.com',
    databaseURL: 'https://gameclass-6f9ab-default-rtdb.firebaseio.com',
    storageBucket: 'gameclass-6f9ab.appspot.com',
    measurementId: 'G-KLB7CZQD69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ7DUC0mDcp7prsnGmRdGk0lCHUYUZH9Q',
    appId: '1:585831821490:android:0a6c5b0c2a560e026899ab',
    messagingSenderId: '585831821490',
    projectId: 'gameclass-6f9ab',
    databaseURL: 'https://gameclass-6f9ab-default-rtdb.firebaseio.com',
    storageBucket: 'gameclass-6f9ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOtZkdmCC91avdX53Lows2nhYdKmoEGdM',
    appId: '1:585831821490:ios:75e3f00b9b06ee516899ab',
    messagingSenderId: '585831821490',
    projectId: 'gameclass-6f9ab',
    databaseURL: 'https://gameclass-6f9ab-default-rtdb.firebaseio.com',
    storageBucket: 'gameclass-6f9ab.appspot.com',
    iosClientId: '585831821490-clebbspq4jqjpnbsemir2pm9na2sm5b2.apps.googleusercontent.com',
    iosBundleId: 'com.example.empreendedorismodigital2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOtZkdmCC91avdX53Lows2nhYdKmoEGdM',
    appId: '1:585831821490:ios:75e3f00b9b06ee516899ab',
    messagingSenderId: '585831821490',
    projectId: 'gameclass-6f9ab',
    databaseURL: 'https://gameclass-6f9ab-default-rtdb.firebaseio.com',
    storageBucket: 'gameclass-6f9ab.appspot.com',
    iosClientId: '585831821490-clebbspq4jqjpnbsemir2pm9na2sm5b2.apps.googleusercontent.com',
    iosBundleId: 'com.example.empreendedorismodigital2',
  );
}
